version: "3.5"
services:
    web:
        build: ./mywebsite
        command: python3 /mywebsite/manage.py runserver 0.0.0.0:8000
        ports:
            - '8000:8000'
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        ports:
            - '5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
